### ISSUE TITLE
Homework 2.5 Error

### ISSUE THREAD

**Issue by Nilex-Shinde** [aurasphere/mongodb-university-classes#3]
In MongoDB Security Course,Homework 2.5
The answer of this homework question is invalid.
Please correct it.

**Comment by aurasphere** [comment]
Hey @Nilex-Shinde can you give me more info? Please keep in mind that the question may have changed.
Thanks!

**Comment by baabhu** [comment]
{ $skip : 25 } should be { $skip : 24 }. We need 25 document. Can't skip 25 to get the correct answer.

**Comment by rogerlau** [comment]
The answer should be:

`{"doc":{"str":"The quick brown fox jumps over the lazy dog"},"isEnabled":true}`

**Comment by aurasphere** [comment]
@rogerlau thanks for the help! I think this is something that has changed in the new version of MongoDB since this was verified with a Shell script provided by their team. I'm going to close it (see README.md contributions section) unless you don't prove me wrong ;) Thanks again!
